name: dist-s1-env
dependencies:
 - python>=3.12
 - pip
 - asf_search
 - backoff
 - click
 - dem_stitcher
 - distmetrics
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - git # older versions of git on servers
 - geopandas
 - jupyterlab
 - matplotlib
 - multiprocess # TODO: Remove once distmetrics on conda - need to add this to conda recipe
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch
 - rasterio
 - ruff
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tile_mate
 - tqdm
 - cudatoolkit>=11.8


