name: dist-s1-env
channels:
 - conda-forge
 - nvidia
dependencies:
 - python>=3.12
 - pip
 - __cuda=11.8
 - asf_search
 - backoff
 - click
 - nvidia::cuda=11.8
 - cudatoolkit=11.8
 - dem_stitcher
 - dist_s1_enumerator
 - distmetrics
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - jupyterlab
 - matplotlib
 - multiprocess # TODO: Remove once distmetrics on conda - need to add this to conda recipe
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch>=2.1.0=cuda118*
 - pyyaml
 - rasterio
 - ruff
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tile_mate>=0.0.12
 - tqdm
