name: dist-s1-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
 - python>=3.12
 - pip
 - asf_search
 - backoff
 - boto3
 - click
 - dem_stitcher
 - dist_s1_enumerator
 - distmetrics
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - jupyterlab
 - matplotlib
 - multiprocess 
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch::pytorch
 - pytorch-cuda>=11.8
 - rasterio
 - ruff
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - cuda-toolkit>=11.8
 - pip:
   - tile-mate>=0.0.12 # TODO: unclear why this is downgraded when in conda-forge
