name: dist-s1-env
channels:
 - conda-forge
dependencies:
 - python>=3.12
 - asf_search
 - backoff
 - click
 - flake8
 - einops # TODO: Remove once distmetrics on conda
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pyarrow
 - pydantic
 - pytest
 - pytest-cov
 - pandera  # TODO: remove once dist-s1-enumerator is on conda
 - pytorch
 - rasterio
 - tqdm
 - setuptools
 - setuptools_scm
 - ruff
 - pip
 - scipy
 - shapely
 - pip:
    - dist-s1-enumerator
    - distmetrics