name: dist-s1-env
channels:
 - conda-forge
dependencies:
 - python>=3.12
 - pip
 - asf_search
 - backoff
 - click
 - dem_stitcher
 - distmetrics
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - jupyterlab
 - matplotlib
 - multiprocess # TODO: Remove once distmetrics on conda - need to add this to conda recipe
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
<<<<<<< HEAD
 - pytorch>=2,<2.6
 - pyyaml
=======
 - pytorch>=2
>>>>>>> 5f13b7f (distmetrics via pypi)
 - rasterio
 - ruff
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - cudatoolkit>=11.8
 - tile_mate>=0.0.12
 - pip:
<<<<<<< HEAD
   - dist_s1_enumerator
   - pyarrow
   - tile-mate>=0.0.12
=======
   - dist-s1-enumerator
   - distmetrics
   - einops
   - pyarrow
>>>>>>> 5f13b7f (distmetrics via pypi)
