name: dist-s1-env
channels:
 - conda-forge
dependencies:
 - python>=3.12
 - asf_search
 - backoff
 - click
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pydantic
 - pytest
 - multiprocess # TODO: Remove once distmetrics on conda - need to add this to conda recipe
 - pytest-cov
 - pytorch
 - rasterio
 - tqdm
 - setuptools
 - setuptools_scm
 - ruff
 - pip
 - scipy
 - shapely
 - dist_s1_enumerator
 - distmetrics
