site_name: DIST-S1 Docs
repo_url: https://github.com/opera-adt/dist-s1
theme:
  name: material
nav:
  - Home: index.md
  - Config Models:
      - AlgoConfigData: config/algoconfig.md
      - RunConfigData: config/runconfig.md
  - Product Documentation:
      - Overview: product_documentation.md
      - Product Layers: product_layers.md
      - Product Models: product_models.md
      - Disturbance Labels: disturbance_labels.md
plugins:
  - search
markdown_extensions:
  - tables
watch:
  - src
