site_name: DIST-S1 Docs
repo_url: https://github.com/opera-adt/dist-s1
theme:
  name: material
nav:
  - Home: index.md
  - API:
      - AlgoConfigData: api/algoconfig.md
      - RunConfigData: api/runconfig.md
plugins:
  - search
markdown_extensions:
  - tables
watch:
  - src
