site_name: DIST-S1 Docs
repo_url: https://github.com/opera-adt/dist-s1
theme:
  name: material
nav:
  - Home: index.md
  - API:
      - AlgoConfigData: api/algoconfig.md
      - RunConfigData: api/runconfig.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_pydantic:
                  schema: true
            docstring_style: numpy
            show_signature_annotations: true
            show_source: false
            members_order: source
            show_bases: false
markdown_extensions:
  - tables
watch:
  - src
