dist-s1 run \
    --mgrs_tile_id '34SGH' \
    --post_date '2024-08-26' \
    --track_number 7 \
    --dst_dir '../notebooks/los-angeles' \
    --memory_strategy 'low' \
    --device 'cpu' \
    --n_workers_for_norm_param_estimation 5 \
    --model_source 'transformer_optimized' \
    --apply_water_mask true \
