name: Deploy MkDocs to GitHub Pages

# Run this workflow every time a new commit is pushed to the 'dev' branch
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: ["3.12"]

    # Grant GITHUB_TOKEN the permissions it needs to deploy to GitHub Pages
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up mamba and install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: dist-s1-env
          cache-environment: true

      - name: Install dist-s1
        shell: bash -l {0}
        run: |
            python -m pip install --no-deps .

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site